require("autopairs")
-- require("buffers") -- not wotking atm
require("colorscheme")
require("grammar")
require("keymaps")
require("lsp")
require("lua-line")
require("nvimtree")
require("options")
require("plugins")
require("telescope")
require("term")
require("treesitter")
require("whichkey")
